root = "."

[build]
  cmd = "go build -o ./bin/server ./cmd/server"
  bin = "./bin/server"
  include_ext = ["go", "tpl", "tmpl", "html", "css", "js"]
  stop_on_error = true

[log]
  time = true

[color]
  app = "yellow"
  build = "cyan"
  main = "magenta"
